### ISSUE TITLE
How to use java6 to load pmml model of LightGBM?

### ISSUE THREAD

**Issue by billbargens** [jpmml/jpmml-lightgbm#1]
I made a pmml model file using the jpmml-lightgbm tool. And I have to use the jpmml-evaluator-1.1.14 to load the model which is compatible with java6. 

But it threw a exception as follows:
```
Exception in thread "main" java.lang.IllegalArgumentException: http://www.dmg.org/PMML-4_3
	at org.jpmml.schema.Version.forNamespaceURI(Version.java:47)
	at org.jpmml.model.PMMLFilter.updateSource(PMMLFilter.java:111)
	at org.jpmml.model.PMMLFilter.startPrefixMapping(PMMLFilter.java:41)
 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startNamespaceMapping(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)
```
So I change the pmml file from 

```   
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
  <PMML xmlns="http://www.dmg.org/PMML-4_3" version="4.3">
  ........
```
to

``` 
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
  <PMML xmlns="http://www.dmg.org/PMML-4_2" version="4.2">
  ........
```

And the testcase passed!

So, are there any hidden problems for this informal method?
Also, is there more formal method to load the pmml model of LightGBM under jdk6 environment?

**Comment by vruusmann** [comment]
After you've exported a LightGBM, XGBoost, Scikit-Learn etc. model to PMML representation, then it becomes decoupled from the source machine learning framework. So, there's nothing LightGBM-specific left here, and this issue should be re-stated as "how do I score PMML schema version 4.3 documents on JDK 1.6".

The correct answer is that you shouldn't be using JDK 1.6 in 2017 anymore, as its End-of-Life has passed (it's been dead for close to four years now).

> I have to use the jpmml-evaluator-1.1.14 to load the model which is compatible with java6.

You should at least upgrade to the latest JPMML-Evaluator 1.1.X version, which is 1.1.20.

Better yet, you might want to check out this JDK 1.6-backport of the JPMML-Evaluator version 1.3.X codebase:
https://github.com/pellmont/jpmml-evaluator/commit/bb14cc028da386cbb182c0940641fab61166a798

> Are there any hidden problems for this informal method?

I wouldn't recommend using JPMML-Evaluator version 1.1.X in production. IIRC, it contains some bugs in the area of scoring of ensemble models, and the performance is also not so good.

The JPMML-LightGBM library is generating "fixed configuration" model data structures. If you have successfully validated predictions for one LightGBM model, then you can safely assume that the predictions will be valid for all other LightGBM models as well.

Please note that the JPMML-Evaluator library contains inspection API, which provides the capability to detect incompatible ("import from future") data structure fragments:
https://github.com/jpmml/jpmml-evaluator/blob/master/features.md#inspection-api

In your case, you should apply Visitor class `org.jpmml.model.visitors.VersionInspector`, and check the version constant that is returned by the `VersionInspector#getMinimum()` method:
https://github.com/jpmml/jpmml-model/blob/master/pmml-model/src/main/java/org/jpmml/model/visitors/VersionInspector.java#L143

If it returns something less than or equal to `Version.PMML_4_2`, then it safe to tweak the XML namespace declaration.

**Comment by vruusmann** [comment]
Related to: https://github.com/jpmml/jpmml-xgboost/issues/12

**Comment by billbargens** [comment]
> Better yet, you might want to check out this JDK 1.6-backport of the JPMML-Evaluator version 1.3.X codebase:
> pellmont/jpmml-evaluator@bb14cc0

So I can use this under the java 6 environment?

**Comment by vruusmann** [comment]
@billbargens This JDK 1.6-backport is not maintained by me.
