### ISSUE TITLE
categorical features support

### ISSUE THREAD

**Issue by guolinke** [jpmml/jpmml-lightgbm#10]
It seems the categorical features isn't supported.
any plans for this ?

**Comment by vruusmann** [comment]
> It seems the categorical features isn't supported.

What is the basis of this observation?

LightGBM-style categorical features should be fully supported, including everything related to `cat_boundaries_` and `cat_threshold_` attributes:
https://github.com/jpmml/jpmml-lightgbm/blob/master/src/main/java/org/jpmml/lightgbm/Tree.java#L315-L325

**Comment by guolinke** [comment]
Thanks for clarification!
