### ISSUE TITLE
Failing when featureInfo is None

### ISSUE THREAD

**Issue by mohit-shrma** [jpmml/jpmml-lightgbm#11]
PMML encoder fails when some of the features are absent or when their featureInfo is None in lightGBM output model. Specifically, it raises exception when it encounters `featureInfo` as None in https://github.com/jpmml/jpmml-lightgbm/blob/master/src/main/java/org/jpmml/lightgbm/GBDT.java#L138

An easy way to reproduce is to use a feature matrix where entire column is None. This scenario happens when due to certain threshold or criteria entire column is dropped .

**Comment by mohit-shrma** [comment]
is this a valid fix for this?
```
if (featureInfo.equals("none")) {
				continue;
			}
```

**Comment by vruusmann** [comment]
What is your LightGBM version? The `HEAD` version of the JPMML-LightGBM library is targeting LightGBM version 2.0.11, and may not be compatible with (much-) earlier versions.

Personally, I haven't seen a reasonably recent LightGBM model file, which does not provide `feature_names` and `feature_infos` attributes. These two attributes are there even if the dataset does not contain any categorical features. For example, see in my `ClassificationIris` integration test model file: https://github.com/jpmml/jpmml-lightgbm/blob/master/src/test/resources/lgbm/ClassificationIris.txt

Could you please share a "broken" LightGBM model file (together with an explanation about how it was generated).

**Comment by mohit-shrma** [comment]
I am using the latest version of lightgbm to train and evaluate models.
It is not broken, its just that during training a feature column was absent and lightgbm chose to write  "None" corresponding to it in model file. I have attached the generated model file and lightgbm binary can read this model file perfectly fine and use it for predictions, I am only having trouble to convert it into PMML file.
[LightGBM_model_1.reg.txt](https://github.com/jpmml/jpmml-lightgbm/files/1567078/LightGBM_model_1.reg.txt)

**Comment by mohit-shrma** [comment]
@vruusmann do you have any updates on this?

**Comment by vruusmann** [comment]
@mohit-shrma Thanks for sharing the sample LightGBM model file, but this issue is currently not a priority for me.
