### ISSUE TITLE
Lightgbm categorical_feature predicate wrong

### ISSUE THREAD

**Issue by zhxt95** [jpmml/jpmml-lightgbm#12]
Hi, Mr. Ruusmann, when I used your 1.1.4 jpmml-lightgbm and successfully got a pmml from a pipeline,  I find following errors in the pmml which makes the Verification failed.
![image](https://user-images.githubusercontent.com/15633297/35077603-323b63a6-fc39-11e7-9f7b-651e76931266.png)
A labelencodered categorical feature is used in this SimpleSetPredicate. As the pmml itself demands，the array type should be "int" . However, the values in the array are actually the string type original values before labelencodered. 
I think there must be some mistakes. 
Did I mistakenly used your tool or there is some bugs?
I read your Java code, and I think maybe the bug is in the encodeFeatures part. I‘m not very sure since  I'm not good at Java. Hope this helps you.

**Comment by vruusmann** [comment]
Thanks for pointing out a bug in the JPMML-SkLearn library. Will figure out why it didn't manifest itself in my integration tests, and then fix it.

**Comment by vruusmann** [comment]
As a workaround, change the data type of categorical columns from `string` to `categorical`, and then remove the `LabelEncoder` transformation from the pipeline. The idea is that LightGBM's Scikit-Learn wrapper is able to detect and encode such columns automatically.

See the following example. First, changing the data type of columns:
https://github.com/jpmml/jpmml-lightgbm/blob/master/src/test/resources/main.py#L9-L10. Then, fitting the LGBMClassifier on the original (ie. non-encoded) dataset: https://github.com/jpmml/jpmml-lightgbm/blob/master/src/test/resources/main.py#L50-L55

**Comment by zhxt95** [comment]
Thanks for your advice, I'll have a try.
