### ISSUE TITLE
Support tweedie and gamma distributions

### ISSUE THREAD

**Issue by thomashan** [jpmml/jpmml-lightgbm#13]

**Comment by vruusmann** [comment]
What are the corresponding objective function names?

The `poisson` objective function is already supported:
https://github.com/jpmml/jpmml-lightgbm/blob/master/src/main/java/org/jpmml/lightgbm/GBDT.java#L456-L457

**Comment by thomashan** [comment]
I haven't tried `poisson` explicitly.
I assumed `poisson` wasn't implemented because I've tried `gamma` and `tweedie` which weren't implemented and they all belong to the exponential family of distributions.

The objective names are `gamma` and `tweedie`.
