### ISSUE TITLE
How to cancel the limits of the value ranges.

### ISSUE THREAD

**Issue by adslwang4601** [jpmml/jpmml-lightgbm#19]
"schema" : {
    "inputFields" : [ {
      "id" : "build_year",
      "dataType" : "double",
      "opType" : "continuous",
      "values" : [ "[0.0, 7.611347717403621]" ]
    }

I am using "openscoring" to deploy my lightgbm model. When the value of  "build_year" is greater than  7.611347717403621 or less than 0.0, the response of the post request is "400". How do I let the deployed model accept the values that are not within the range?

**Comment by vruusmann** [comment]
This question has been answered here: https://github.com/jpmml/jpmml-evaluator/issues/145#issuecomment-465066718
