### ISSUE TITLE
Error: Could not find or load main class org.jpmml.lightgbm.Main

### ISSUE THREAD

**Issue by 77QingLiu** [jpmml/jpmml-lightgbm#21]
`Error: Could not find or load main class org.jpmml.lightgbm.Main`
java 1.8 version. don't know why anyone could help with this? very appreciate that. Thanks

**Comment by vruusmann** [comment]
Download the latest release version here: https://github.com/jpmml/jpmml-lightgbm/releases/download/1.2.6/jpmml-lightgbm-executable-1.2.6.jar

If you uncompress the JAR archive, then you will find an `org.jpmml.lightgbm.Main` class in there. It means that everything has been packaged and released correctly, and the problem, if any, happens on your side.

**Comment by 77QingLiu** [comment]
@vruusmann thanks, I forget to clone this web site thus enter this issue.
I think to add a `git clone` note in the readme.md will be good.
thanks for building such an amazing package.
