### ISSUE TITLE
how to transform a lightgbm model into a regression model

### ISSUE THREAD

**Issue by xxyy001** [jpmml/jpmml-lightgbm#38]
Excuse me, how to transform a lightgbm model into a regression model

**Comment by xxyy001** [comment]
{FieldName@3221} "_target" -> {ProbabilityDistribution@3266} "ProbabilityDistribution{result=0, probability_entries=[1=0.4350043361208059, 0=0.5649956638791941]}"

It is now a classification model after conversion

**Comment by vruusmann** [comment]
The JPMML-LightGBM library does not change model type during conversion (eg. from regression to classification).

If the converter is giving you a classification-type model in PMML, then it means that it was applied to a classification-type LightGBM model text file.

To obtain a regression-type model in LightGBM and PMML, simply use a regression-type objective function (eg. `regression` or `regression_l1`).
