### ISSUE TITLE
ref #27 #22

### ISSUE THREAD

**Issue by etveritas** [jpmml/jpmml-lightgbm#39]
#22 #27 
Hello, I also encounter this problem. And I count the pandas_categorical number is right, but when convert, it also out of bounds.where could the redundant number from?

**Comment by vruusmann** [comment]
You're referencing CLOSED issues, without providing an adequate technical explanation/evidence of what's the actual problem.

May I suggest you to update to the latest version of the JPMML-LightGBM library first?
