### ISSUE TITLE
import project, cannot find "PandasCategoricalParser"

### ISSUE THREAD

**Issue by yuzhixing** [jpmml/jpmml-lightgbm#42]
"PandasCategoricalParser" in "GBDT", where is from?

**Comment by vruusmann** [comment]
The `org.jpmml.lightgbm.PandasCategoricalParser` class is generated by the JavaCC tool during the project build.

Run Apache Maven command `mvn clean package`, and you shall find this class under the `target/generated-sources/javacc` directory.

**Comment by yuzhixing** [comment]
thanks
