### ISSUE TITLE
Broken tests

### ISSUE THREAD

**Issue by Goorman** [jpmml/jpmml-lightgbm#6]
Trying to build this library according to manual, it builds fine but fails to pass classifier tests:

<img width="1436" alt="screen shot 2017-11-08 at 14 07 40" src="https://user-images.githubusercontent.com/3996740/32545914-3c4e409e-c48e-11e7-9eb8-a27d710de56d.png">

[org.jpmml.lightgbm.ClassificationTest.txt](https://github.com/jpmml/jpmml-lightgbm/files/1453605/org.jpmml.lightgbm.ClassificationTest.txt)

Built it with -Dskiptests flag for now, but this is probably something you would want to fix.

OS: mac os 10.13 

P.S: Since the difference is in 15th digit or something like that, you could check not for exact equality but for approximate equality with small tolerance 1e-10.

**Comment by vruusmann** [comment]
The build succeeds using Java 1.7 and 1.8 on 64-bit LInux.

The "aspiration" for exact reproducibility between LightGBM and (J)PMML predictions is intentional - this helps me to detect regressions during version updates/upgrades.
