### ISSUE TITLE
Use `long` to represent `unsigned int` attributes

### ISSUE THREAD

**Issue by vruusmann** [jpmml/jpmml-lightgbm#9]
The `cat_threshold` attribute may take values that exceed the numeric range of the `int` data type:
https://groups.google.com/d/msg/jpmml/10uOILNhXY8/wpWrAJjrCQAJ

**Comment by IanUtley** [comment]
Patch I used to read unsigned ints using larger datatype (long)
[cat_threshold.txt](https://github.com/jpmml/jpmml-lightgbm/files/1560258/cat_threshold.txt)
